# fly.toml app configuration file generated for mercadonapromotions-twilight-rain-2817 on 2023-11-17T12:13:58+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mercadonapromotions-twilight-rain-2817"
primary_region = "cdg"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
